allowHostPorts: false
priority: null
requiredDropCapabilities:
  - ALL
allowPrivilegedContainer: false
runAsUser:
  type: MustRunAsRange
users: 
  - 'system:serviceaccount:<namespace>:default'
  - 'system:serviceaccount:<namespace>:arcgis-prometheus-serviceaccount'
  - 'system:serviceaccount:<namespace>:arcgis-admin-serviceaccount'
  - 'system:serviceaccount:<namespace>:arcgis-queue-serviceaccount'
  - 'system:serviceaccount:<namespace>:arcgis-ingress-serviceaccount'
allowHostDirVolumePlugin: false
seccompProfiles:
  - runtime/default
allowHostIPC: false
seLinuxContext:
  type: MustRunAs
readOnlyRootFilesystem: false
metadata:
  name: restricted-v2-esri
fsGroup:
  type: MustRunAs
  ranges:
  - min: 117932853
    max: 117932853
groups: []
kind: SecurityContextConstraints
defaultAddCapabilities: null
supplementalGroups:
  type: RunAsAny
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - ephemeral
  - nfs
  - persistentVolumeClaim
  - projected
  - secret
allowHostPID: false
allowHostNetwork: false
allowPrivilegeEscalation: false
apiVersion: security.openshift.io/v1
allowedCapabilities:
  - NET_BIND_SERVICE
