apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-esri
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
