{
 "title": "Services Usage Statistics Summary By Folder Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "folderName", "label": "Folder Name", "query": { "query": "label_values(folderName)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate of Requests",
   "type": "graph",
   "description": "Rate of Requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (requests{folderName=\"$folderName\"}[5m]))",
     "legendFormat": "$folderName"
    }
   ]
  },
  {
   "title": "Average Request Response Times In Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(requests_response_time_seconds_sum{folderName=\"$folderName\"}[5m]))/sum (rate(requests_response_time_seconds_count{folderName=\"$folderName\"}[5m]))",
     "legendFormat": "$folderName"
    }
   ]
  },
  {
   "title": "Rate of Succeeded / Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (requests_succeeded{folderName=\"$folderName\"}[5m]))",
     "legendFormat": "$folderName"
    },
    {
     "expr": "sum (rate (requests_failed{folderName=\"$folderName\"}[5m]))",
     "legendFormat": "$folderName"
    }
   ]
  },
  {
   "title": "Rate of Requests Usage / Wait Timed Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (requests_wait_timedout{folderName=\"$folderName\"}[5m]))",
     "legendFormat": "$folderName"
    },
    {
     "expr": "sum (rate (requests_usage_timedout{folderName=\"$folderName\"}[5m]))",
     "legendFormat": "$folderName"
    }
   ]
  }
 ]
}