{
 "title": "Service Usage Statistics Comparison Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "serviceName1", "label": "Service 1", "query": { "query": "label_values(serviceName)" } },
   { "name": "serviceName2", "label": "Service 2", "query": { "query": "label_values(serviceName)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate of Requests",
   "type": "graph",
   "description": "Rate of Requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (requests{serviceName=\"$serviceName1\"}[5m]))",
     "legendFormat": "$serviceName1"
    },
    {
     "expr": "sum (rate (requests{serviceName=\"$serviceName2\"}[5m]))",
     "legendFormat": "$serviceName2"
    }
   ]
  },
  {
   "title": "Average Request Response Times In Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(requests_response_time_seconds_sum{serviceName=\"$serviceName1\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName1\"}[5m]))",
     "legendFormat": "$serviceName1"
    },
    {
     "expr": "sum (rate(requests_response_time_seconds_sum{serviceName=\"$serviceName2\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName2\"}[5m]))",
     "legendFormat": "$serviceName2"
    }
   ]
  },
  {
   "title": "Rate of Succeeded / Failed Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate (requests_succeeded{serviceName=\"$serviceName1\"}[5m]))",
     "legendFormat": "$serviceName1 - Succeeded"
    },
    {
     "expr": "sum (rate (requests_failed{serviceName=\"$serviceName1\"}[5m]))",
     "legendFormat": "$serviceName1 - Failed"
    },
    {
     "expr": "sum(rate (requests_succeeded{serviceName=\"$serviceName2\"}[5m]))",
     "legendFormat": "$serviceName2 - Succeeded"
    },
    {
     "expr": "sum (rate (requests_failed{serviceName=\"$serviceName2\"}[5m]))",
     "legendFormat": "$serviceName2 - Failed"
    }
   ]
  },
  {
   "title": "Rate of Requests Usage / Wait Timed Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (requests_wait_timedout{serviceName=\"$serviceName1\"}[5m]))",
     "legendFormat": "$serviceName1 - wait timedout"
    },
    {
     "expr": "sum (rate (requests_usage_timedout{serviceName=\"$serviceName1\"}[5m]))",
     "legendFormat": "$serviceName1 - usage timedout"
    },
    {
     "expr": "sum (rate (requests_wait_timedout{serviceName=\"$serviceName2\"}[5m]))",
     "legendFormat": "$serviceName2 - wait timedout"
    },
    {
     "expr": "sum (rate (requests_usage_timedout{serviceName=\"$serviceName2\"}[5m]))",
     "legendFormat": "$serviceName2 - usage timedout"
    }
   ]
  }
 ]
}