{
 "title": "Service Response Time Percentages",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "serviceName", "label": "Service Name", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "Operation", "query": { "query": "label_values(operation)" } }
  ]
 },
 "panels": [
  {
   "title": "< 0.05 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"0.05\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 0.1 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"0.1\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 0.25 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"0.25\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 0.5 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"0.5\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 0.75 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"0.75\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 1 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"1.0\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 2.5 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"2.5\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 5.0 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"5.0\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 7.5 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"7.5\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "< 10 seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_bucket{le=\"10.0\",serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))*100) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  }
 ]
}