{
 "title": "Service Usage Statistics by Operation",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "serviceName", "label": "Service Name", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "Operation", "query": { "query": "label_values(operation)" } }
  ]
 },
 "panels": [
  {
   "title": "Rate of Requests",
   "type": "timeseries",
   "description": "Rate of Requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum (rate (requests_total{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "Average Request Response Times In Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_sum{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "Rate of Succeeded / Failed Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate (requests_succeeded_total{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    },
    {
     "expr": "(sum (rate (requests_failed_total{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "Rate of Requests Usage / Wait Timed Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum (rate (requests_wait_timedout_total{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    },
    {
     "expr": "(sum (rate (requests_usage_timedout_total{serviceName=\"$serviceName\", operation=\"$operation\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  }
 ]
}