{
 "title": "Summary of Asynchronous Geoprocessing Service Usage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": {
     "query": "label_values({serviceType=\"GPServer\"},serviceName)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Job Submission Time In Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_sum{serviceName=\"$serviceName\",operation=\"submitJob\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\",operation=\"submitJob\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "Average Job Wait Time In Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum (rate(gp_job_wait_time_seconds_sum{serviceName=\"$serviceName\"}[5m]))/sum (rate(gp_job_wait_time_seconds_count{serviceName=\"$serviceName\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "Rate of Job Status Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(rate (requests_total{serviceName=\"$serviceName\", operation=\"getJobStatus\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  },
  {
   "title": "Average Job Execution Time In Seconds",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum (rate(requests_response_time_seconds_sum{serviceName=\"$serviceName\",operation=\"executeJob\"}[5m]))/sum (rate(requests_response_time_seconds_count{serviceName=\"$serviceName\",operation=\"executeJob\"}[5m]))) or on() vector(0)",
     "legendFormat": "$serviceName"
    }
   ]
  }
 ]
}