apiVersion: "rbac.authorization.k8s.io/v1"
kind: "Role"
metadata:
  name: "deployment-role"
  namespace: "arcgis"
rules:
  # secrets
  - apiGroups: [ "" ]
    resources: [ "secrets" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write

  # configmaps
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write

  # leases
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write

  # services
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write
  - apiGroups: [ "" ]
    resources: [ "services/status" ]
    verbs: [ "get", "list", "watch" ] # read only

  # pods
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write, but we dont manage it, except for delete when cleanup
  - apiGroups: [ "" ]
    resources: [ "pods/status" ]
    verbs: [ "get", "list", "watch" ] # read only
  - apiGroups: [ "" ]
    resources: [ "pods/log" ]
    verbs: [ "get", "list", "watch" ] # read only, not used now, will be helpful in understanding failures later

  # persistentvolumeclaims
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write
  - apiGroups: [ "" ]
    resources: [ "persistentvolumeclaims/status" ]
    verbs: [ "get", "list", "watch" ] # read only

  # deployments
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write
  - apiGroups: [ "apps" ]
    resources: [ "deployments/status" ]
    verbs: [ "get", "list", "watch" ] # read only
  - apiGroups: [ "apps" ]
    resources: [ "deployments/scale" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write, not used now
  - apiGroups: [ "apps" ]
    resources: [ "deployments/rollback" ]
    verbs: [ "create", "delete", "deletecollection", "patch", "update" ] # write only, not used now

  # replicasets
  - apiGroups: [ "apps" ]
    resources: [ "replicasets" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write, not used much
  - apiGroups: [ "apps" ]
    resources: [ "replicasets/status" ]
    verbs: [ "get", "list", "watch" ] # read only, not used now
  - apiGroups: [ "apps" ]
    resources: [ "replicasets/scale" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write, not used now

  # statefulsets
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets/status" ]
    verbs: [ "get", "list", "watch" ] # read only
  - apiGroups: [ "apps" ]
    resources: [ "statefulsets/scale" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write, not used now

  # ingress
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write
  - apiGroups: [ "networking.k8s.io" ]
    resources: [ "ingresses/status" ]
    verbs: [ "get", "list", "watch" ] # read only

  # jobs
  - apiGroups: [ "batch" ]
    resources: [ "jobs" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write
  - apiGroups: [ "batch" ]
    resources: [ "jobs/status" ]
    verbs: [ "get", "list", "watch" ] # read only

  # horizontalpodautoscalers
  - apiGroups: [ "autoscaling" ]
    resources: [ "horizontalpodautoscalers" ]
    verbs: [ "get", "list", "watch", "create", "delete", "deletecollection", "patch", "update" ] # read write, not used now
  - apiGroups: [ "autoscaling" ]
    resources: [ "horizontalpodautoscalers/status" ]
    verbs: [ "get", "list", "watch" ] # read only, not used now

  # events
  - apiGroups: [ "" ]
    resources: [ "events" ]
    verbs: [ "get", "list", "watch", "create", "patch" ] # read write, ingress-controller needs write access

  # resourcequotas
  - apiGroups: [ "" ]
    resources: [ "resourcequotas" ]
    verbs: [ "get", "list", "watch" ] # read only, not used now, will be helpful in understanding failures later
  - apiGroups: [ "" ]
    resources: [ "resourcequotas/status" ]
    verbs: [ "get", "list", "watch" ] # read only, not used now, will be helpful in understanding failures later

  # endpoints
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "get", "list", "watch" ] # read only

  # endpointslices
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "endpointslices" ]
    verbs: [ "get", "list", "watch" ] # read only

  # namespaces
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get" ]

  # serviceaccounts
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "get", "list", "watch", "create", "delete"  ]

  # roles
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "roles" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]

  # rolebindings
  - apiGroups: [ "rbac.authorization.k8s.io" ]
    resources: [ "rolebindings" ]
    verbs: [ "get", "list", "watch", "create", "delete" ]
