apiVersion: v1
kind: PersistentVolume
metadata:
  name: arcgis-enterprise-folder-pv-2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: arcgis
    name: my-local-pvc
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  local:
    path: /path/to/service/data
  nodeAffinity: # The node affinity part is optional if you have the data on all the nodes in your cluster
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: serviceType
          operator: In
          values:
          - byReferenceMap