apiVersion: v1
kind: PersistentVolume
metadata:
  name: arcgis-enterprise-folder-pv-1
  labels:
    serviceType: byReferenceMap
    shareType: NFS
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: example-nfs-server.domain.com
    path: /share/path/to/service/data
  storageClassName: arcgis-folder-pv