apiVersion: v1
kind: PersistentVolume
metadata:
  name: arcgis-enterprise-Windows-smb-pv
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  csi:
    driver: smb.csi.k8s.io
    volumeAttributes:
      source: //example-SMB-server.domain.com/shared/path/to/service/data
    volumeHandle: smb-pv-handle # provide a name here
    nodeStageSecretRef:
      name: smb-csi-secret-my-org 
      namespace: default
  mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - vers=3.0
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem